# Generated by Django 4.1.3 on 2022-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('weight', models.FloatField(null=True)),
                ('waist', models.FloatField(null=True)),
                ('stomach', models.FloatField(null=True)),
                ('chest', models.FloatField(null=True)),
                ('butt', models.FloatField(null=True)),
                ('thighs', models.FloatField(null=True)),
                ('calves', models.FloatField(null=True)),
                ('code_written', models.FloatField(null=True)),
            ],
        ),
    ]
