# Generated by Django 4.1.3 on 2022-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tracker_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='spendings',
            field=models.JSONField(null=True),
        ),
    ]
