# Generated by Django 4.1.3 on 2022-12-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tracker_spendings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='gym_workout',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='sa_practice',
            field=models.BooleanField(null=True),
        ),
    ]
