# Generated by Django 4.1.3 on 2022-12-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tracker_gym_workout_tracker_sa_practice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='spendings',
            new_name='spending',
        ),
    ]
